# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - angular-scala-shop-client

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e98f47c19d4e4be9a941fc75afac7457 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_929053d3ce68409e97564b2ea23d71d2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e98f47c19d4e4be9a941fc75afac7457 }}/scala-play-angular-shop_my-client:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'angular-scala-shop-client'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9cbdb07ea5ef456ebed48c96c812c15b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e98f47c19d4e4be9a941fc75afac7457 }}/scala-play-angular-shop_my-client:${{ github.sha }}'